### ISSUE TITLE
Icon wird nicht geladen

### ISSUE THREAD

**Issue by garyee** [BugBuster1701/contao-cron#23]
Hallo,

das Icon für Backend wird nicht geladen. (Probiert mit Contao 3.2.x & 3.4.4)
Warum wird denn das icon nicht direkt in der config.php eingebunden?

Grüße

**Comment by BugBuster1701** [comment]
Das Icon ist er Trigger für die Cron Ausführung. Wenn das Icon nicht erscheint, läuft irgendwas schief bei der Ausführung der Cron Jobs. Entweder die dauern zu lange oder brechen ab.
Mal die Fehlermeldungen einschalten und prüfen ob Meldungen kommen diesbezüglich.

**Comment by garyee** [comment]
AH ... okay coole Idee :)

**Comment by BugBuster1701** [comment]
Bei mir gings grad auch nicht, lag daran dass die DB nicht aktualisiert war. (manuelle Installation)
