### ISSUE TITLE
Lange Fehlermeldung bei manueller Ausführung

### ISSUE THREAD

**Issue by 31er** [BugBuster1701/contao-cron#25]
Ich nutze Contao-Cron, um in Verbindung mit BackupDB von der Datenbank regelmäßige Backups zu erstellen.

Unter Contao 3.5 mit Composer-Client erzeugt Contao-Cron 3.3.1 bei manueller Ausführung über den Button „Job sofort starten“ eine rund 185.000 Zeilen lange Fehlermeldung, die im Wesentlichen aus den folgenden Zeile besteht:

Notice: Undefined index: admin in /hosting/testweb/system/modules/core/classes/BackendUser.php on line 179
Notice: Undefined index: precision in /hosting/testweb/system/modules/BackupDB/BackupDbCommon.php on line 200
Notice: Undefined index: length in /hosting/testweb/system/modules/BackupDB/BackupDbCommon.php on line 199
Notice: Undefined variable: fieldlist in /hosting/testweb/system/modules/BackupDB/BackupDbCommon.php on line 314
Notice: Undefined index: admin in /hosting/testweb/system/modules/core/classes/BackendUser.php on line 179
Notice: Undefined index: rangeFilter in /hosting/testweb/system/modules/haste/library/Haste/Dca/DateRangeFilter.php on line 42
Notice: Undefined index: relation in /hosting/testweb/system/modules/haste/library/Haste/Model/Relations.php on line 622
Notice: Undefined index: inputType in /hosting/testweb/system/modules/core/library/Contao/DcaExtractor.php on line 505
Notice: Undefined index: group in /hosting/testweb/system/modules/core/library/Contao/Model/QueryBuilder.php on line 75
Notice: Undefined index: having in /hosting/testweb/system/modules/core/library/Contao/Model/QueryBuilder.php on line 81
[22-Jul-2015 11:11:16] Manually scheduler job complete

Die Fehlermeldung wird angezeigt, wenn unter Einstellungen die Option „Fehlermeldungen anzeigt“ aktiviert ist. Der Datenbank-Dump mittels BackupDB wird aber korrekt erstellt.

**Comment by BugBuster1701** [comment]
Besseren Error Level setzen in:
https://github.com/BugBuster1701/contao-cron/blob/master/public/CronController.php#L183
https://github.com/BugBuster1701/contao-cron/blob/master/public/CronStart.php#L168

**Comment by BugBuster1701** [comment]
E_ALL & ~E_NOTICE
