### ISSUE TITLE
PHP warning on first manual execute

### ISSUE THREAD

**Issue by garyee** [BugBuster1701/contao-cron#28]
Hello,

I configured a cronjob and then started it manually (by clicking on the little symbol). I got the php waring:

```
PHP Warning: copy(/public_html/neu2016/files/AutoBackupDB/.htaccess): failed to open stream: No such file or directory in public_html/neu2016/system/modules/BackupDB/AutoBackupDB.php on line 58
#0 [internal function]: __error(2, 'copy(public_html/neu2...', 'public_html/neu2...', 58, Array)
#1 public_html/neu2016/system/modules/BackupDB/AutoBackupDB.php(58): copy('public_html/neu2...', 'public_html/neu2...')
#2 /public_html/neu2016/system/modules/BackupDB/AutoBackupDB.php(131): AutoBackupDb->run()
#3 /public_html/neu2016/system/modules/cron/public/CronStart.php(171): include('public_html/neu2...')
#4 /public_html/neu2016/system/modules/cron/public/CronStart.php(133): CronStart->runJob(Object(Contao\Database\Mysqli\Result))
#5 /public_html/neu2016/system/modules/cron/public/CronStart.php(183): CronStart->run()
#6 {main}
```

It did not come up again, just the first time

**Comment by do-while** [comment]
Hi garyee,

which version of Contao do you use?
have you installed BackupDB via extension repository or with composer?

In the error line 58 BackupDB generates a .htaccess in the directory for AutoBackupDB. Two possible reasons for an error:
1) Do you have deleted the AutoBackupDB directory in files/ ?
2) Is there no file htacc in the BackupDB directory system/modules/BackupDB ?

Try to repair the BackupDB extension with update-repair.

**Comment by garyee** [comment]
Hi,

Contao Version is 3.5.17 and BackupDB is installed via composer (conato-legacy package)
1. No
2. That is more likely.

It is working now. Thank you.
